name: calorie_app_danika
description: A new Flutter project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  http: ^1.0.0
  firebase_auth: ^4.6.3
  firebase_database: ^10.2.3
  firebase_messaging: ^14.6.3
  flutter_signin_button: ^2.0.0
  google_sign_in: ^6.1.4
  camera: ^0.10.5+2
  path_provider: ^2.0.15
  path: ^1.8.3
  intl: ^0.18.1
  firebase_storage: ^11.2.8
  image_picker: ^1.0.8
  google_fonts: 6.1.0
  tflite_flutter: ^0.10.2
  image: ^4.1.3
  syncfusion_flutter_charts: ^24.1.44+1
  provider: ^6.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_barcode_scanner: ^2.0.0
  font_awesome_flutter: ^9.2.0
  health: ^10.2.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon_ios.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  # web:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  # windows:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "path/to/image.png"

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/flippers-alpha.png



