// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-aTR8mGuPM1QcFCEoBrYh3SxJdH7XdKg',
    appId: '1:15920923300:web:164b7abd0ec07acfbe9c31',
    messagingSenderId: '15920923300',
    projectId: 'inspiring-quotes-9e078',
    authDomain: 'inspiring-quotes-9e078.firebaseapp.com',
    databaseURL: 'https://inspiring-quotes-9e078-default-rtdb.firebaseio.com',
    storageBucket: 'inspiring-quotes-9e078.appspot.com',
    measurementId: 'G-S3YRGJFWEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBbvFhISpLPk25nFAMnzLytduqdKMb4XA',
    appId: '1:15920923300:android:b0c1a7fecbcdb4b4be9c31',
    messagingSenderId: '15920923300',
    projectId: 'inspiring-quotes-9e078',
    databaseURL: 'https://inspiring-quotes-9e078-default-rtdb.firebaseio.com',
    storageBucket: 'inspiring-quotes-9e078.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQNeVhFj9pZ9vL1smB2yv4xYmudM-Zq3M',
    appId: '1:15920923300:ios:72d38eebcc95d075be9c31',
    messagingSenderId: '15920923300',
    projectId: 'inspiring-quotes-9e078',
    databaseURL: 'https://inspiring-quotes-9e078-default-rtdb.firebaseio.com',
    storageBucket: 'inspiring-quotes-9e078.appspot.com',
    iosClientId: '15920923300-dirolm88fuvvv1mlgkr6bg2e3ps6jhde.apps.googleusercontent.com',
    iosBundleId: 'com.codingminds.caloriedanika.calorieAppDanika',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQNeVhFj9pZ9vL1smB2yv4xYmudM-Zq3M',
    appId: '1:15920923300:ios:a370b836a064ef9dbe9c31',
    messagingSenderId: '15920923300',
    projectId: 'inspiring-quotes-9e078',
    databaseURL: 'https://inspiring-quotes-9e078-default-rtdb.firebaseio.com',
    storageBucket: 'inspiring-quotes-9e078.appspot.com',
    iosClientId: '15920923300-3g2r31r3moaupv8ieteb3r90s75qj3h8.apps.googleusercontent.com',
    iosBundleId: 'com.codingminds.caloriedanika.calorieAppDanika.RunnerTests',
  );
}